### ISSUE TITLE
Bundle ID 建議

### ISSUE THREAD

**Issue by PichuChen** [Ptt-official-app/Ptt-iOS#16]
目前我看到 Bundle ID 是 org.ptt.ptt

我覺得這個東西可以討論，所以開個 ISSUE 來讓大家討論。

我初步的構想有以下選項：
* tw.edu.ntu.ptt.app
* cc.ptt.app
* tw.org.ptt.app
* tw.ptt.app

以上。

**Comment by denkeni** [comment]
Similar issue: https://github.com/Ptt-official-app/Ptt-Android/issues/126
