### ISSUE TITLE
Toolbar is missing when navigating to SingleArticleViewController

### ISSUE THREAD

**Issue by denkeni** [Ptt-official-app/Ptt-iOS#89]
Cause: https://github.com/Ptt-official-app/Ptt-iOS/blob/71a4a3adc4165ad19bb5fcc2441f5334401e5caf/Ptt/Flows/BoardFlow/Controllers/BoardViewController.swift#L95

Ref: https://t.me/c/1400788359/687

**Comment by jhsiao21** [comment]
Added a test video.
https://github.com/Ptt-official-app/Ptt-iOS/assets/27193487/56ee1a85-d189-42bf-a816-5e62621ca34a
